# deploy

name: Deploy App

on:
  workflow_dispatch:

env:
  bundle-id: org.gacco.t7-mobile

jobs:
  deploy:
    runs-on: macos-11

    steps:
    - run: echo ${{github.ref}}

    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - run: sudo xcode-select -s /Applications/Xcode_12.5.1.app

    - uses: Apple-Actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12_BASE64 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

    - uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: ${{ env.bundle-id }}
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

    - name: Change PRODUCT_BUNDLE_IDENTIFIER/PROVISIONING_PROFILE_SPECIFIER
      run: sed -i '' 's/org.edx.mobile/${{ env.bundle-id }}/g' ./edX.xcodeproj/project.pbxproj

    - name: xcodebuild archive
      run: xcodebuild -workspace edx.xcworkspace -scheme edX -configuration Release -archivePath ./archive.xcarchive archive
      env:
        CURRENT_PROJECT_VERSION: ${{ github.run_number }}

    - name: xcodebuild export
      run: xcodebuild -exportArchive -archivePath ./archive.xcarchive -exportPath ./export -exportOptionsPlist ExportOptions.plist

    - uses: apple-actions/upload-testflight-build@v1
      with: 
        app-path: 'export/edx.ipa' 
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}

#    - run: echo "This job's status is ${{ job.status }}."
