# deploy

name: Deploy App

on:
  workflow_dispatch:
    inputs:
      task:
        type: choice
        description: gradle task
        options: 
        - xcodebuild
        - bundleProdDebug

jobs:
  deploy:
    runs-on: macos-11

    steps:
    - name: Show inputs
      run: |
        echo "task: ${{ github.event.inputs.task }}"

    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Setup - Xcode
      run: sudo xcode-select -s /Applications/Xcode_12.5.1.app

    - name: Setup - Ruby and bundler dependencies
      uses: ruby/setup-ruby@v1.57.0
      with:
        ruby-version: 2.4.0
        bundler-cache: true

    - name: Cache - cocoapods
      id: cache-cocoapods
      uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: ${{ runner.os }}-pods-

    - name: Install - cocoapods
      run: pod install --repo-update

    - uses: Apple-Actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12_BASE64 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

    - uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: org.gacco.mobile.jast.test
        profile-type: IOS_APP_STORE
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

#    - name: Change PRODUCT_BUNDLE_IDENTIFIER
#      run: sed -i '' 's/org.edx.mobile/org.gacco.mobile.jast.test/g' ./edX.xcodeproj/project.pbxproj

    - name: Build | xcodebuild archive
      run: >
        xcodebuild 
          -workspace edx.xcworkspace 
          -scheme edX 
          -configuration Release 
          -archivePath .build/Archives/edX.xcarchive 
          PRODUCT_BUNDLE_IDENTIFIER = org.gacco.mobile.jast.test
          PROVISIONING_PROFILE_SPECIFIER = JAST-TestFlight-Distribution
          CURRENT_PROJECT_VERSION = ${{ github.run_number }} 
          archive
#      run: set -o pipefail && xcodebuild -configuration Release archive -archivePath ./archive | xcpretty
#      run: xcodebuild -exportArchive -archivePath archive -exportPath archive -exportOptionsPlist debugExportOptions.plist
#      run: xcodebuild -workspace edx.xcworkspace -scheme edX -configuration Release archive -archivePath ./archive

#    - name: Build #繝薙Ν繝碓K
#      run: xcodebuild -workspace edx.xcworkspace -scheme edX -sdk iphonesimulator

#    - name: Build
#      run: xcodebuild -configuration Release build

    - run: echo "This job's status is ${{ job.status }}."
