# deploy

name: deploy

on:
  workflow_dispatch:
    inputs:
      bundle-id:
        type: choice
        description: bundle-id
        options: 
        - org.gacco.mobile.feature
      input-ref:
        type: message
        description: ref

env:
  bundle-id: ${{ github.event.inputs.bundle-id }}

jobs:
  deploy:
    runs-on: macos-11

    steps:
    - run: echo ${{github.ref}}

    - run: echo "bundle-id=org.gacco.mobile.develop" >> $GITHUB_ENV
      if: contains(github.ref, 'develop')

    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.input-ref }}
        persist-credentials: false

    - run: sudo xcode-select -s /Applications/Xcode_12.5.1.app

    - uses: Apple-Actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12_BASE64 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

    - uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: ${{ env.bundle-id }}
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

    - name: change bundle-id
      run: |
        sed -i '' 's/org.gacco.mobile/${{ env.bundle-id }}/g' ./edX.xcodeproj/project.pbxproj
        sed -i '' 's/org.gacco.mobile/${{ env.bundle-id }}/g' ./ExportOptions.plist

    - uses: poad/xcode-build-number-auto-update@v1
      with:
        path: ./Source/edX-Info.plist
        new-number: ${{ github.run_number }}

    - name: xcodebuild archive
      run: xcodebuild -workspace edx.xcworkspace -scheme edX -configuration Release -archivePath ./archive.xcarchive archive

    - name: xcodebuild export
      run: xcodebuild -exportArchive -archivePath ./archive.xcarchive -exportPath ./export -exportOptionsPlist ExportOptions.plist

    - uses: apple-actions/upload-testflight-build@v1
      with: 
        app-path: 'export/edx.ipa' 
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

#    - run: echo "This job's status is ${{ job.status }}."
