name: test

on:
  workflow_dispatch:
    inputs:
      bundle-id:
        type: choice
        description: bundle-id
        options: 
        - org.gacco.mobile.feature

env:
  bundle-id: ${{ github.event.inputs.bundle-id }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{github.ref}}
      - name: Set bundle-id
        if: "!contains(github.ref, 'master')"
        run: echo "bundle-id=org.gacco.mobile" >> $GITHUB_ENV
      - run: echo "bundle-id=org.gacco.mobile.develop" >> $GITHUB_ENV
        if: contains(github.ref, 'develop')
        
      - run: echo "${{ env.bundle-id }}"
