name: test

on:
  workflow_dispatch:

env:
  bundle-id: org.gacco.t7-mobile

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set bundle-id
        if: "!contains(github.ref, 'master')"
        run: export bundle-id=org.gacco.mobile
      - name: Set bundle-id
        if: contains(github.ref, 'develop')
        run: export bundle-id=org.gacco.mobile.develop
      - run: echo $bundle-id
