name: test

on:
  workflow_dispatch:

env:
  bundle-id: org.gacco.t7-mobile

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{github.ref}}
      - name: Set bundle-id
        if: "!contains(github.ref, 'master')"
        run: echo "bundle-id=org.gacco.mobile" >> $GITHUB_ENV
#      - name: Set bundle-id
#        if: contains(github.ref, 'develop')
#        run: echo "bundle-id=org.gacco.mobile.develop" >> $GITHUB_ENV
      - run: echo "${{ env.bundle-id }}"
