name: test

on:
  workflow_dispatch:

env:
  bundle-id: org.gacco.t7-mobile

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set bundle-id
        if: "!contains(github.ref, 'master')"
        run: echo "org.gacco.mobile" >> $bundle-id
      - name: Set bundle-id
        if: contains(github.ref, 'develop')
        run: echo "org.gacco.mobile.develop" >> $bundle-id
      - run: echo $bundle-id
